"""initial tables

Revision ID: 2c85c9300d22
Revises: 
Create Date: 2026-03-05 21:18:18.007952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c85c9300d22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('dance_styles', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_source_id'), 'artists', ['source_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Enum('international', 'national', 'local', name='event_level'), nullable=True),
    sa.Column('dance_styles', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_source_id'), 'events', ['source_id'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('dance_styles', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_source_id'), 'groups', ['source_id'], unique=True)
    op.create_table('guestbook_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('pin_code', sa.String(length=6), nullable=True),
    sa.Column('pin_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_reports_source_id'), 'battle_reports', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_battle_reports_source_id'), table_name='battle_reports')
    op.drop_table('battle_reports')
    op.drop_table('guestbook_messages')
    op.drop_index(op.f('ix_groups_source_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_events_source_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_artists_source_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
